name: Tests
on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'
    - uses: actions/checkout@v3
    - name: Build all
      run: |
        make
        ls -al ./out/c2w
        if ldd ./out/c2w ; then echo "must be static binary" ; exit 1 ; fi

  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: |
        CUR=$PWD
        cd ..
        echo == Cloning evacchi/wazero
        git clone https://github.com/evacchi/wazero
        cd wazero
        WAZERO=$PWD
        echo == Checkout branch poll-oneoff-cancel
        git checkout poll-oneoff-cancel
        cd $CUR
        echo == Mod replace in project root
        go mod edit -replace="github.com/tetratelabs/wazero=$WAZERO"
        go mod tidy
        cd tests/wazero
        echo == Mod replace in tests/wazero
        go mod edit -replace="github.com/tetratelabs/wazero=$WAZERO"
        go mod tidy
        cd $CUR
        echo == Start real tests
        make test

  # benchmark:
  #   runs-on: ubuntu-22.04
  #   name: Benchmark
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Benchmark
  #     run: |
  #       make benchmark

  linter:
    runs-on: ubuntu-22.04
    name: Linter
    steps:
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52
        args: --verbose

  project:
    name: Project Checks
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
    - name: "Check DCO sign"
      run: |
        go install github.com/vbatts/git-validation@v1.2.0
        git-validation -v -run DCO
